# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 567dfa3d12b3719641c758d9377c9dbad6b7ef2c6f9ef0533b83382869dfd3c1bd3260a9044c208293e44e04cf8e0bfa21dca5b88ed50fc376baf02d08e07e72

test:
  secret_key_base: 14cb480c50ee035fdfad0197e2f7749c856164eb020032b3db4d715643fe4e9de43e8531ce2f00f6444159911fd465cf84eb97c6fcbe35d6264ccf87d33183c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
